
package org.example.registraduria;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;




/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Registraduria", targetNamespace = "http://www.example.org/Registraduria/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Registraduria {
 

    /**
     * 
     * @param parameters
     * @return
     *     returns org.example.registraduria.RegistroUsuarioResp
     */
    @WebMethod(operationName = "RegistroUsuario", action = "http://www.example.org/registraduria/registroUsuario")
    @WebResult(name = "RegistroUsuarioResp", targetNamespace = "http://www.example.org/Registraduria/", partName = "parameters")
    public RegistroUsuarioResp registroUsuario(
        @WebParam(name = "RegistroUsuarioReq", targetNamespace = "http://www.example.org/Registraduria/", partName = "parameters")
        RegistroUsuarioReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.example.registraduria.LoginUsuarioResp
     */
    @WebMethod(operationName = "LoginUsuario", action = "http://www.example.org/registraduria/login")
    @WebResult(name = "LoginUsuarioResp", targetNamespace = "http://www.example.org/Registraduria/", partName = "parameters")
    public LoginUsuarioResp loginUsuario(
        @WebParam(name = "LoginUsuarioReq", targetNamespace = "http://www.example.org/Registraduria/", partName = "parameters")
        LoginUsuarioReq parameters);

   

    /**
     * 
     * @param parameters
     * @return
     *     returns org.example.registraduria.ConsultaAntecedentesResp
     */
    @WebMethod(operationName = "ConsultaAntecedentes", action = "http://www.example.org/registraduria/consultaAntecedentes")
    @WebResult(name = "ConsultaAntecedentesResp", targetNamespace = "http://www.example.org/Registraduria/", partName = "parameters")
    public ConsultaAntecedentesResp consultaAntecedentes(
        @WebParam(name = "ConsultaAntecedentesReq", targetNamespace = "http://www.example.org/Registraduria/", partName = "parameters")
        ConsultaAntecedentesReq parameters);

}
