
package org.example.funcionarios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Funcionarios", targetNamespace = "http://www.example.org/Funcionarios/", wsdlLocation = "file:/C:/Users/MauricioTascon/Documents/NetBeansProjects/ConsultaFuncionario/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/Funcionarios.wsdl")
public class Funcionarios_Service
    extends Service
{

    private final static URL FUNCIONARIOS_WSDL_LOCATION;
    private final static WebServiceException FUNCIONARIOS_EXCEPTION;
    private final static QName FUNCIONARIOS_QNAME = new QName("http://www.example.org/Funcionarios/", "Funcionarios");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/MauricioTascon/Documents/NetBeansProjects/ConsultaFuncionario/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/Funcionarios.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FUNCIONARIOS_WSDL_LOCATION = url;
        FUNCIONARIOS_EXCEPTION = e;
    }

    public Funcionarios_Service() {
        super(__getWsdlLocation(), FUNCIONARIOS_QNAME);
    }

    public Funcionarios_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FUNCIONARIOS_QNAME, features);
    }

    public Funcionarios_Service(URL wsdlLocation) {
        super(wsdlLocation, FUNCIONARIOS_QNAME);
    }

    public Funcionarios_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FUNCIONARIOS_QNAME, features);
    }

    public Funcionarios_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Funcionarios_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Funcionarios
     */
    @WebEndpoint(name = "FuncionariosSOAP")
    public Funcionarios getFuncionariosSOAP() {
        return super.getPort(new QName("http://www.example.org/Funcionarios/", "FuncionariosSOAP"), Funcionarios.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Funcionarios
     */
    @WebEndpoint(name = "FuncionariosSOAP")
    public Funcionarios getFuncionariosSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/Funcionarios/", "FuncionariosSOAP"), Funcionarios.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FUNCIONARIOS_EXCEPTION!= null) {
            throw FUNCIONARIOS_EXCEPTION;
        }
        return FUNCIONARIOS_WSDL_LOCATION;
    }

}
