
package org.example.registraduria;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Registraduria", targetNamespace = "http://www.example.org/Registraduria/", wsdlLocation = "file:/C:/Users/mauriciotascon/Documents/NetBeansProjects/Registradurai/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/Registraduria.wsdl")
public class Registraduria_Service
    extends Service
{

    private final static URL REGISTRADURIA_WSDL_LOCATION;
    private final static WebServiceException REGISTRADURIA_EXCEPTION;
    private final static QName REGISTRADURIA_QNAME = new QName("http://www.example.org/Registraduria/", "Registraduria");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/mauriciotascon/Documents/NetBeansProjects/Registradurai/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/Registraduria.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTRADURIA_WSDL_LOCATION = url;
        REGISTRADURIA_EXCEPTION = e;
    }

    public Registraduria_Service() {
        super(__getWsdlLocation(), REGISTRADURIA_QNAME);
    }

    public Registraduria_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTRADURIA_QNAME, features);
    }

    public Registraduria_Service(URL wsdlLocation) {
        super(wsdlLocation, REGISTRADURIA_QNAME);
    }

    public Registraduria_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTRADURIA_QNAME, features);
    }

    public Registraduria_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Registraduria_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Registraduria
     */
    @WebEndpoint(name = "RegistraduriaSOAP")
    public Registraduria getRegistraduriaSOAP() {
        return super.getPort(new QName("http://www.example.org/Registraduria/", "RegistraduriaSOAP"), Registraduria.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Registraduria
     */
    @WebEndpoint(name = "RegistraduriaSOAP")
    public Registraduria getRegistraduriaSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/Registraduria/", "RegistraduriaSOAP"), Registraduria.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTRADURIA_EXCEPTION!= null) {
            throw REGISTRADURIA_EXCEPTION;
        }
        return REGISTRADURIA_WSDL_LOCATION;
    }

}
